---
title: "benchmark_ROC"
author: "Delmas Maxime"
date: "03/02/2022"
output: html_document
---
```{r setup, include=FALSE}
library(tidyverse)
library(pROC)
library(ggplot2)
library(DT)
```


```{r}

path <- "data/SiameseBERT"
list_dir <- c("batch128_m5_th1")
K <- 5

data_auc <- data.frame()

for(k in 1:K){
  
  data <- data.frame()
  
  for(dir in list_dir){
    DPATH_untrained <- paste0( c(path, "no-train", paste0("f", k), "best_model_predictions.csv"), collapse = '/' )
    DPATH_trained <- paste0( c(path, dir, paste0("f", k), "best_model_predictions.csv"), collapse = '/' )
    
    D_train <- read.table(DPATH_trained, header = T, sep = ',')
    roc_train <- roc(predictor = D_train$pwdist, response = D_train$y, levels = c('0', '1'), direction = '>')
    
    D_notrain <- read.table(DPATH_untrained, header = T, sep = ',')
    roc_notrain <- roc(predictor = D_notrain$pwdist, response = D_notrain$y, levels = c('0', '1'), direction = '>')
    
    c_train <- coords(roc_train, "all", ret = c("threshold", "fpr", "tpr")) %>% mutate(model = dir, trained = TRUE)
    c_notrain <- coords(roc_notrain, "all", ret = c("threshold", "fpr", "tpr")) %>% mutate(model = dir, trained = FALSE)
    
    data <- bind_rows(data, c_train, c_notrain)
    data_auc <- bind_rows(data_auc, data.frame(K = k, model = dir, train = c(TRUE, FALSE), AUC = c(auc(roc_train), auc(roc_notrain))))
    print(data_auc)
    
  }
  
  g <- ggplot(data, aes(x = fpr, y = tpr, color = model, linetype = trained)) + 
  geom_line(size = 1) + 
  geom_abline(intercept = 0, slope = 1, color="red", linetype="dashed") +
  scale_linetype_manual(values=c("twodash", "dotted")) +
  xlab("True Positive Rate (TPR)") + 
  ylab("Precision") + 
  ggtitle(paste0(c("ROC Fold: ", k))) + 
  theme_classic() +
  theme(text = element_text(size = 35), 
        title = element_text(size = 25))
  plot(g)
  
}

datatable(data_auc)
```


